/**
 * Tipagem e dados Mock para o módulo de Novidades.
 * Centraliza o schema para evitar quebra de componentes.
 */
import { NoveltyWithDetails, NoveltyStatsDisplay } from './useNovelties';

const NOVELTY_WINDOW_DAYS = 30;

function getDaysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

const MOCK_SUPPLIERS = [
  { id: 'sup-1', name: 'Premium Gifts Co.', code: 'PREM' },
  { id: 'sup-2', name: 'EcoFriendly Solutions', code: 'ECO' },
  { id: 'sup-3', name: 'TechInnovate', code: 'TECH' },
];

const MOCK_CATEGORIES = [
  { id: 'cat-1', name: 'Eletrônicos' },
  { id: 'cat-2', name: 'Escritório' },
  { id: 'cat-3', name: 'Vestuário' },
];

// Garante que MOCK_NOVELTIES segue estritamente o NoveltyWithDetails
export const MOCK_NOVELTIES: NoveltyWithDetails[] = [
  {
    novelty_id: 'n-1',
    product_id: 'p-1',
    product_sku: 'TECH-001',
    product_name: 'Power Bank Solar 20000mAh',
    product_description: 'Carregador solar de alta capacidade para brindes tecnológicos.',
    base_price: 159.90,
    product_image: 'https://images.unsplash.com/photo-1619441207978-3d326c46e2c9?auto=format&fit=crop&q=80&w=400',
    category_id: 'cat-1',
    category_name: 'Eletrônicos',
    supplier_id: 'sup-3',
    supplier_name: 'TechInnovate',
    supplier_code: 'TECH',
    supplier_product_code: 'SLR-20',
    detected_at: getDaysAgo(0), // Hoje
    expires_at: getDaysAgo(-30),
    days_remaining: 30,
    status: 'active',
    is_highlighted: true,
    is_active: true,
    stock_quantity: 150,
    min_quantity: 20,
    stock_status: 'in-stock',
  },
  {
    novelty_id: 'n-2',
    product_id: 'p-2',
    product_sku: 'ECO-045',
    product_name: 'Kit Escrita Sustentável Bambu',
    product_description: 'Conjunto de caneta e lapiseira em bambu reflorestado.',
    base_price: 45.00,
    product_image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=400',
    category_id: 'cat-2',
    category_name: 'Escritório',
    supplier_id: 'sup-2',
    supplier_name: 'EcoFriendly Solutions',
    supplier_code: 'ECO',
    supplier_product_code: 'BMB-KIT',
    detected_at: getDaysAgo(1), // Ontem
    expires_at: getDaysAgo(-29),
    days_remaining: 29,
    status: 'active',
    is_highlighted: true,
    is_active: true,
    stock_quantity: 500,
    min_quantity: 50,
    stock_status: 'in-stock',
  },
  {
    novelty_id: 'n-3',
    product_id: 'p-3',
    product_sku: 'PREM-992',
    product_name: 'Mochila Executiva Anti-Furto',
    product_description: 'Mochila com compartimento oculto e saída USB.',
    base_price: 289.00,
    product_image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=400',
    category_id: 'cat-3',
    category_name: 'Vestuário',
    supplier_id: 'sup-1',
    supplier_name: 'Premium Gifts Co.',
    supplier_code: 'PREM',
    supplier_product_code: 'EXE-BAG',
    detected_at: getDaysAgo(5),
    expires_at: getDaysAgo(-25),
    days_remaining: 25,
    status: 'active',
    is_highlighted: true,
    is_active: true,
    stock_quantity: 15,
    min_quantity: 20,
    stock_status: 'low-stock',
  },
  {
    novelty_id: 'n-4',
    product_id: 'p-4',
    product_sku: 'TECH-552',
    product_name: 'Fone Bluetooth Noise Cancelling',
    product_description: 'Fone de ouvido premium com cancelamento de ruído.',
    base_price: 320.00,
    product_image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=400',
    category_id: 'cat-1',
    category_name: 'Eletrônicos',
    supplier_id: 'sup-3',
    supplier_name: 'TechInnovate',
    supplier_code: 'TECH',
    supplier_product_code: 'BT-NC',
    detected_at: getDaysAgo(12),
    expires_at: getDaysAgo(-18),
    days_remaining: 18,
    status: 'active',
    is_highlighted: false,
    is_active: true,
    stock_quantity: 0,
    min_quantity: 10,
    stock_status: 'out-of-stock',
  },
  {
    novelty_id: 'n-5',
    product_id: 'p-5',
    product_sku: 'ECO-881',
    product_name: 'Garrafa Térmica Aço Inox 750ml',
    product_description: 'Garrafa térmica com parede dupla e acabamento fosco.',
    base_price: 89.90,
    product_image: 'https://images.unsplash.com/photo-1602143399827-bd934344c5c1?auto=format&fit=crop&q=80&w=400',
    category_id: 'cat-2',
    category_name: 'Escritório',
    supplier_id: 'sup-2',
    supplier_name: 'EcoFriendly Solutions',
    supplier_code: 'ECO',
    supplier_product_code: 'SS-750',
    detected_at: getDaysAgo(25),
    expires_at: getDaysAgo(-5),
    days_remaining: 5,
    status: 'expiring_soon',
    is_highlighted: false,
    is_active: true,
    stock_quantity: 200,
    min_quantity: 30,
    stock_status: 'in-stock',
  },
  {
    novelty_id: 'n-6',
    product_id: 'p-6',
    product_sku: 'PREM-123',
    product_name: 'Agenda 2024 Couro Sintético',
    product_description: 'Agenda premium com capa texturizada e fecho magnético.',
    base_price: 65.00,
    product_image: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&q=80&w=400',
    category_id: 'cat-2',
    category_name: 'Escritório',
    supplier_id: 'sup-1',
    supplier_name: 'Premium Gifts Co.',
    supplier_code: 'PREM',
    supplier_product_code: 'AG-24',
    detected_at: getDaysAgo(28),
    expires_at: getDaysAgo(-2),
    days_remaining: 2,
    status: 'expiring_soon',
    is_highlighted: false,
    is_active: true,
    stock_quantity: 80,
    min_quantity: 20,
    stock_status: 'in-stock',
  }
];

// Garante que MOCK_STATS segue estritamente o NoveltyStatsDisplay
export const MOCK_STATS: NoveltyStatsDisplay = {
  totalNovelties: 120,
  activeNovelties: 42,
  expiringSoon: 8,
  totalProducts: 1500,
  noveltyRate: 3,
  arrivedToday: 5,
  arrivedThisWeek: 18,
  arrivedLast15Days: 32,
  topSupplierName: 'TechInnovate',
  topSupplierCount: 15,
};
