import { test, expect } from 'vitest';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

test.describe('Audit System Consistency', () => {

  test('ci-audit-gen.cjs should execute without errors', () => {
    const output = execSync('node scripts/ci-audit-gen.cjs').toString();
    expect(output).toContain('Artifacts successfully updated');
  });

  test('generate-final-dossier.cjs should create a valid PDF', () => {
    const pdfPath = 'mnt/documents/FINAL_ENTERPRISE_AUDIT_REPORT.pdf';
    
    // Ensure file exists
    expect(fs.existsSync(pdfPath)).toBeTruthy();
    
    // Basic sanity: PDF header magic numbers
    const buffer = fs.readFileSync(pdfPath);
    expect(buffer.slice(0, 4).toString()).toBe('%PDF');
  });

  test('Markdown dossier should have dynamic Evidence Genesis populated', () => {
    const mdContent = fs.readFileSync('FINAL_ENTERPRISE_AUDIT_REPORT.md', 'utf8');
    
    // Check if the table headers generated by git are present
    expect(mdContent).toContain('| Funcionalidade | Data de Geração | Versão Ref | Commit Ref | Auditor Original |');
    
    // Ensure we have at least some rows with commit hashes
    const commitHashes = mdContent.match(/`[a-f0-9]{7}`/g);
    expect(commitHashes?.length).toBeGreaterThan(0);
  });

  test('Should fail if a broken path is introduced', () => {
    const mdPath = 'FINAL_ENTERPRISE_AUDIT_REPORT.md';
    const originalContent = fs.readFileSync(mdPath, 'utf8');
    
    try {
      // Temporarily inject a broken path
      fs.writeFileSync(mdPath, originalContent + '\n`src/non-existent-file.ts`');
      
      expect(() => {
        execSync('node scripts/ci-audit-gen.cjs', { stdio: 'pipe' });
      }).toThrow();
      
    } finally {
      // Restore original content
      fs.writeFileSync(mdPath, originalContent);
    }
  });
});
